language : node_js

node_js:
  - "12"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
- yarn install

git:
  depth: 1

stages:
  - name: Build
  - name: Test
  - name: Deploy

jobs:
  include:
    - stage: Test
      if: branch = master
      script:
        - node --version
        - yarn --version
        - echo "Testing Started ..."
        - yarn test
        - echo "Testing Finished."

    - stage: Deploy
      if: branch = master
      before_deploy:
        - echo "Build Started ..."
        - yarn build
        - echo "Build Finished."
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        cleanup: false
        skip_cleanup: true
        on:
          branch: master

notifications:
  email:
    if: branch = master
    recipients:
      - "$NPM_EMAIL"
    on_success: change
    on_failure: always
